### Variables
# @baseUrl = https://b8ok804ocwcos8g0ww08k4go.coolify.agnieve.com
@baseUrl = http://localhost:3007
@authToken = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydmNhRk1abHhSdldCUjNuZlRMSGx2MVg4MjIiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJlbWFpbCI6ImRldkBhZ25pZXZlLmNvbSIsImV4cCI6MTc0NTQ4OTU5OSwiZnZhIjpbMCwtMV0sImlhdCI6MTc0NTQ4OTUzOSwiaXNzIjoiaHR0cHM6Ly9idXJzdGluZy1nbnUtMzMuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiYmMxZTMzOTQ3OWY5NTEwZmZlZjYiLCJsYXN0X3NpZ25faW5fYXQiOjE3NDU0ODk1MzgsIm5iZiI6MTc0NTQ4OTUyOSwic2lkIjoic2Vzc18yd0Fmd2ZkNmFnejVoTG9jSjJVQkxSS2VNU00iLCJzdWIiOiJ1c2VyXzJ3Mm1idEdUbFpLUm9uRWxRNUpqdTk0Zm10ZSIsInVzZXJfaWQiOiJ1c2VyXzJ3Mm1idEdUbFpLUm9uRWxRNUpqdTk0Zm10ZSJ9.aiPQk1WaIgc9zabDvJRIYo-BFNltno9Ujb1j4BXInaXBLiinqtB-sdC6tj-Z3QdGzb2niPt1zt73D8vRZ9DNjhDUB-p6x574EhBpQpKJii6_zeIImN4wN-KuAhZC7W_OFnU0VjlXfYlobq0bKrjI5Y6Qs0zsnPLfGIYFuddB-Hs0eXUiNjy_02j5sk2mk19jfOIUOGl9aV9WFBSqNOKjEzwMMVDZlLWePhAJI9QOccXebEH0ozxz8ThZTRu_NuR4AbIpk4ya3eddwZDKXUT55ySE2MIQ_4m81QIh3SlOBvO39TxtYuyeSmNTolt3wZkf6JNEFZf29PZKj3DtHeKE9A


### Authentication test endpoint
GET {{baseUrl}}/auth-test
Authorization: Bearer {{authToken}}

### Get current user information
GET {{baseUrl}}/me
Authorization: Bearer {{authToken}}

### Register as admin
POST {{baseUrl}}/register-admin
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "admin_password": "YOUR_ADMIN_PASSWORD"
}